primera versión plantilla
JJ/pelooxtreem pull request #26
Opened 2022-11-25 08:10 UTC by PabloSpiegel

Si alguien quiese aportar algo o puntualizar algo sin problema.

2022-11-25 08:13 UTC, JJ requested changes
Mira un par de cosillas, por favor.

2022-11-25 08:13 UTC, JJ commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] El código del PR sigue las convenciones de nombres de TypeScrypt.
Esto más bien sería apuntar al `CONTRIBUTING.md` y preguntar si se ha seguido. Todavía no existe, pero cuando exista.

2022-11-25 08:13 UTC, JJ commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] No se han generado nuevos conflictos ni warnings con el código del PR.
Yo creo que esto es innecesario, va de suyo.

2022-11-25 08:29 UTC, JJ requested changes
Hum, no estará en el mismo directorio, tendrás que poner el URL completo.

2022-11-25 08:29 UTC, JJ commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] He mirado [CONTRIBUTING.md](JJ/pelooxtreem/CONTRIBUTING.md) que se sigan los principios
directamente el nombre del fichero, no hace falta el path completo. Estará en este mismo directorio.

2022-11-25 09:15 UTC, JJ submitted a review, later dismissed
Pero deja lo del issue, hombre. Es importante que se diga a qué issue o issues se refiere.

2022-11-25 09:28 UTC, fjgallardo00 requested changes
Te he dejado una cosilla para que la arregles @PabloSpiegel

2022-11-25 09:28 UTC, fjgallardo00 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] He mirado [CONTRIBUTING.md](https://github.com/JJ/pelooxtreem/CONTRIBUTING.md) que se sigan los principios mencionados.
El path de la URL al archivo CONTRIBUTING.md no es correcto. El path debe ser JJ/pelooxtreem/blob/main/CONTRIBUTING.md

2022-11-28 17:28 UTC, JJ commented
Ya no puedo aprobarlo porque tengo un commit en el PR...

2022-11-29 06:30 UTC, PabloSpiegel commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] He mirado [CONTRIBUTING.md](https://github.com/JJ/pelooxtreem/CONTRIBUTING.md) que se sigan los principios mencionados.
Lo acabo de arreglar.Gracias porel apunte :)

2022-12-02 07:59 UTC, JJ commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Me he esperado a que pasen los tests antes de hacer el PR.
"hacer" no, dejar...

2022-12-02 08:44 UTC, vdeq79 approved these changes

2022-12-02 08:48 UTC, fjgallardo00 approved these changes

2022-12-02 09:05 UTC, merged