Feat(servicio.ts): Added pair name-time #22
JJ/pelooxtreem pull request #33
Opened 2022-11-25 08:51 UTC by LuisMart7

Se ha creado Servicio. Por favor revisadlo cada uno por si os hace falta para vuestras implementaciones.

2022-11-25 09:11 UTC, alvarogaro commented on src/servicio.ts
> +export type Servicio = {
Iba a sugerirlo pero ya he visto el cambio :+1: :zap: :es:

2022-11-25 09:15 UTC, alvarogaro approved these changes
:qatar: :+1:

2022-11-25 09:22 UTC, luistf24 requested changes

2022-11-25 09:22 UTC, luistf24 commented on src/servicio.ts
> +  tiempo: string;
Buenas!!Esto yo diría que tendría que ser un objeto de la clase TiempoServicio

2022-11-25 09:27 UTC, LuisMart7 commented on src/servicio.ts
> +  tiempo: string;
Okay. El nombre que define el servicio lo mantenemos como un campo de nuestra clase y elimináis el vuestro.

2022-11-25 10:04 UTC, luistf24 commented on src/servicio.ts
> +  tiempo: string;
:ok_hand: :ok_hand: :ok_hand:

2022-11-25 12:06 UTC, JJ commented
¿Con qué issues va esto?

2022-12-02 09:20 UTC, PacoCP5 commented
Todo lo que se ha tratado en este PR ya se ha solucionado en #51 y #56

2022-12-02 09:20 UTC, closed without merging