Configuracion de las herramientas.
JJ/pelooxtreem pull request #39
Opened 2022-11-25 09:15 UTC by MarinoFajardo

En el fichero de configuración deno.js aparece al final una sección task, en esta sección se añaden las tareas que puede realizar el task runner. Hay que tener cuidado cuando incluimos una tarea, ya que se usa un ssubset de sh/bash para ejecutar las tareas.
Con este shell en estos momentos no soporta los glob, aunque nos indican que lo incorporarán en el futuro.

2022-11-25 09:27 UTC, pedromarting3 approved these changes
Todo bien 👍🏻. Ha sido útil revisar este PR, no sabía que deno se puede usar asi!🥶🥳

2022-11-25 10:37 UTC, JJ requested changes
Me parece bien en principio, pero 
1. habría que documentarlo en el README.md #29 
2. Justificar las diferentes elecciones, no usar simplemente el ejemplo
3. Usar todas las tareas que efectivamente se soliciten. `fmt` no estoy tan seguro. Si se quiere, debería crearse un issue que lo comente.

2022-11-25 10:37 UTC, JJ commented on deno.json
> +    "allowJs": true,
En principio no vamos a permitir JS, sólo TypeScript, ¿no? ¿O es por alguna otra razón?

2022-11-25 10:37 UTC, JJ commented on deno.json
> +      "exclude": ["src/tests/"]
¿Por qué? Habría que hacer linting en todo.

2022-11-25 10:37 UTC, JJ commented on deno.json
> +      "exclude": ["no-unused-vars"]
¿Por qué? Yo dejaría todas las que hay por defecto.

2022-11-25 10:37 UTC, JJ commented on deno.json
> +  "fmt": {
¿Esto qué hace?

2022-12-02 08:03 UTC, alvarogaro approved these changes

2022-12-02 08:17 UTC, JJ approved these changes
🥇

2022-12-02 08:27 UTC, merged